// File: std_generate.cpp
// Description: This C++ program demonstrates the usage of the std::generate algorithm from the C++ Standard Library.
//              The std::generate algorithm is used to fill a range with values generated by a given function or functor.

#include <algorithm>
#include <iostream>
#include <vector>

// Functor to generate values for the std::generate algorithm
struct Generator
{
    int currentValue = 0;

    // Overload the function call operator to generate values
    int operator()()
    {
        return currentValue++;
    }
};

int main()
{
    // Create a vector of integers
    std::vector<int> numbers(5);

    // Use std::generate with the Generator functor to fill the vector with values
    std::generate(numbers.begin(), numbers.end(), Generator());

    // Print the vector after filling it with generated values
    std::cout << "Generated vector: ";
    for (const auto &num : numbers)
    {
        std::cout << num << " ";
    }
    std::cout << std::endl;

    return 0;
}
